/**
 * Localization for the openpublictransport card.
 * Uses hass.language to select the right strings.
 */

const translations: Record<string, Record<string, string>> = {
  en: {
    now: "now",
    in_min: "in {min} min",
    in_1_min: "in 1 min",
    no_departures: "No departures available",
    no_trip_data: "No trip data available",
    entity_unavailable: "Entity is unavailable",
    please_define_entity: "Please define an entity",
    alternative_connections: "Alternative Connections",
    connection_at_risk: "Connection at risk",
    risk: "risk",
    risk_low: "Low risk",
    risk_medium: "Medium risk",
    risk_high: "High risk",
    min_transfer: "Transfer time",
    transfer: "Transfer",
    transfers: "transfers",
    platform: "Pl.",
    time: "Time",
    line: "Line",
    destination: "Destination",
    track: "Track",
    table_layout: "Table (Departure Board)",
    compact_layout: "Compact (Chips)",
    trip_layout: "Trip (Journey)",
    next_layout: "Next Departure (Widget)",
    entity: "Entity",
    layout: "Layout",
    theme: "Theme",
    theme_ha: "Home Assistant (native)",
    max_departures: "Max Departures",
    show_header: "Show Header",
    show_platform: "Show Platform",
    show_delay: "Show Delay",
    show_realtime: "Show Realtime Indicator",
    display_options: "Display Options",
    line_filter: "Line Filter",
    line_filter_hint: "Show only these lines (comma-separated, e.g. U6, S1, RE5). Leave empty to show all.",
    destination_filter: "Destination Filter",
    destination_filter_hint: "Show only departures whose destination matches (comma-separated, partial match, e.g. Duisburg, Flughafen). Leave empty to show all.",
    filters: "Filters",
    trip_filter_note: "The line and destination filters apply to departure boards only. Filter connections on the device itself: Settings → Devices & services → your trip device → Configure.",
  },
  de: {
    now: "jetzt",
    in_min: "in {min} min",
    in_1_min: "in 1 min",
    no_departures: "Keine Abfahrten verfügbar",
    no_trip_data: "Keine Verbindungsdaten verfügbar",
    entity_unavailable: "Entity nicht verfügbar",
    please_define_entity: "Bitte eine Entity auswählen",
    alternative_connections: "Alternative Verbindungen",
    connection_at_risk: "Anschluss gefährdet",
    risk: "Risiko",
    risk_low: "Geringes Risiko",
    risk_medium: "Mittleres Risiko",
    risk_high: "Hohes Risiko",
    min_transfer: "Umstiegszeit",
    transfer: "Umstieg",
    transfers: "Umstiege",
    platform: "Gl.",
    time: "Zeit",
    line: "Linie",
    destination: "Ziel",
    track: "Gleis",
    table_layout: "Tabelle (Abfahrtstafel)",
    compact_layout: "Kompakt (Chips)",
    trip_layout: "Verbindung (Trip)",
    next_layout: "Nächste Abfahrt (Widget)",
    entity: "Entity",
    layout: "Layout",
    theme: "Design",
    theme_ha: "Home Assistant (nativ)",
    max_departures: "Max. Abfahrten",
    show_header: "Kopfzeile anzeigen",
    show_platform: "Gleis anzeigen",
    show_delay: "Verspätung anzeigen",
    show_realtime: "Echtzeit-Indikator anzeigen",
    display_options: "Anzeigeoptionen",
    line_filter: "Linienfilter",
    line_filter_hint: "Nur diese Linien anzeigen (kommagetrennt, z.B. U6, S1, RE5). Leer lassen für alle.",
    destination_filter: "Zielfilter",
    destination_filter_hint: "Nur Abfahrten mit passendem Ziel anzeigen (kommagetrennt, Teiltreffer, z.B. Duisburg, Flughafen). Leer lassen für alle.",
    filters: "Filter",
    trip_filter_note: "Linien- und Zielfilter gelten nur für Abfahrtstafeln. Verbindungen filterst du am Gerät selbst: Einstellungen → Geräte & Dienste → dein Trip-Gerät → Konfigurieren.",
  },
  fr: {
    now: "maintenant",
    in_min: "dans {min} min",
    in_1_min: "dans 1 min",
    no_departures: "Aucun départ disponible",
    no_trip_data: "Aucune donnée de trajet disponible",
    entity_unavailable: "Entité indisponible",
    please_define_entity: "Veuillez sélectionner une entité",
    alternative_connections: "Correspondances alternatives",
    connection_at_risk: "Correspondance menacée",
    risk: "risque",
    risk_low: "Risque faible",
    risk_medium: "Risque moyen",
    risk_high: "Risque élevé",
    min_transfer: "Temps de correspondance",
    transfer: "Correspondance",
    transfers: "correspondances",
    platform: "Voie",
    time: "Heure",
    line: "Ligne",
    destination: "Destination",
    track: "Voie",
    table_layout: "Tableau (Panneau de départs)",
    compact_layout: "Compact (Puces)",
    trip_layout: "Trajet (Itinéraire)",
    next_layout: "Prochain départ (Widget)",
    entity: "Entité",
    layout: "Disposition",
    theme: "Thème",
    theme_ha: "Home Assistant (natif)",
    max_departures: "Départs max.",
    show_header: "Afficher l'en-tête",
    show_platform: "Afficher la voie",
    show_delay: "Afficher le retard",
    show_realtime: "Afficher l'indicateur temps réel",
    display_options: "Options d'affichage",
    line_filter: "Filtre de lignes",
    line_filter_hint: "Afficher uniquement ces lignes (séparées par des virgules, ex. U6, S1, RE5). Laisser vide pour tout afficher.",
    destination_filter: "Filtre de destination",
    destination_filter_hint: "Afficher uniquement les départs dont la destination correspond (séparées par des virgules, correspondance partielle, ex. Duisburg, Aéroport). Laisser vide pour tout afficher.",
    filters: "Filtres",
    trip_filter_note: "Les filtres de lignes et de destination ne s'appliquent qu'aux tableaux de départs. Filtrez les trajets sur l'appareil lui-même : Paramètres → Appareils et services → votre appareil de trajet → Configurer.",
  },
  nl: {
    now: "nu",
    in_min: "over {min} min",
    in_1_min: "over 1 min",
    no_departures: "Geen vertrekken beschikbaar",
    no_trip_data: "Geen reisgegevens beschikbaar",
    entity_unavailable: "Entity niet beschikbaar",
    please_define_entity: "Selecteer een entity",
    alternative_connections: "Alternatieve verbindingen",
    connection_at_risk: "Aansluiting in gevaar",
    risk: "risico",
    risk_low: "Laag risico",
    risk_medium: "Gemiddeld risico",
    risk_high: "Hoog risico",
    min_transfer: "Overstaptijd",
    transfer: "Overstap",
    transfers: "overstappen",
    platform: "Spoor",
    time: "Tijd",
    line: "Lijn",
    destination: "Bestemming",
    track: "Spoor",
    table_layout: "Tabel (Vertrekbord)",
    compact_layout: "Compact (Chips)",
    trip_layout: "Reis (Route)",
    next_layout: "Volgend vertrek (Widget)",
    entity: "Entity",
    layout: "Layout",
    theme: "Thema",
    theme_ha: "Home Assistant (native)",
    max_departures: "Max. vertrekken",
    show_header: "Koptekst tonen",
    show_platform: "Spoor tonen",
    show_delay: "Vertraging tonen",
    show_realtime: "Realtime-indicator tonen",
    display_options: "Weergaveopties",
    line_filter: "Lijnfilter",
    line_filter_hint: "Toon alleen deze lijnen (kommagescheiden, bijv. U6, S1, RE5). Leeg laten voor alles.",
    destination_filter: "Bestemmingsfilter",
    destination_filter_hint: "Toon alleen vertrekken met een overeenkomende bestemming (kommagescheiden, gedeeltelijke overeenkomst, bijv. Duisburg, Luchthaven). Leeg laten voor alles.",
    filters: "Filters",
    trip_filter_note: "Lijn- en bestemmingsfilters gelden alleen voor vertrekborden. Filter verbindingen op het apparaat zelf: Instellingen → Apparaten en diensten → je reis-apparaat → Configureren.",
  },
  sv: {
    now: "nu",
    in_min: "om {min} min",
    in_1_min: "om 1 min",
    no_departures: "Inga avgångar tillgängliga",
    no_trip_data: "Inga resedata tillgängliga",
    entity_unavailable: "Entitet otillgänglig",
    please_define_entity: "Välj en entitet",
    alternative_connections: "Alternativa förbindelser",
    connection_at_risk: "Anslutning hotad",
    risk: "risk",
    risk_low: "Låg risk",
    risk_medium: "Medelrisk",
    risk_high: "Hög risk",
    min_transfer: "Bytestid",
    transfer: "Byte",
    transfers: "byten",
    platform: "Spår",
    time: "Tid",
    line: "Linje",
    destination: "Destination",
    track: "Spår",
    table_layout: "Tabell (Avgångstavla)",
    compact_layout: "Kompakt (Chips)",
    trip_layout: "Resa (Rutt)",
    next_layout: "Nästa avgång (Widget)",
    entity: "Entitet",
    layout: "Layout",
    theme: "Tema",
    theme_ha: "Home Assistant (native)",
    max_departures: "Max avgångar",
    show_header: "Visa rubrik",
    show_platform: "Visa spår",
    show_delay: "Visa försening",
    show_realtime: "Visa realtidsindikator",
    display_options: "Visningsalternativ",
    line_filter: "Linjefilter",
    line_filter_hint: "Visa bara dessa linjer (kommaseparerade, t.ex. U6, S1, RE5). Lämna tomt för alla.",
    destination_filter: "Destinationsfilter",
    destination_filter_hint: "Visa bara avgångar vars destination matchar (kommaseparerade, delvis matchning, t.ex. Duisburg, Flygplats). Lämna tomt för alla.",
    filters: "Filter",
    trip_filter_note: "Linje- och destinationsfiltren gäller bara avgångstavlor. Filtrera förbindelser på själva enheten: Inställningar → Enheter och tjänster → din reseenhet → Konfigurera.",
  },
  pl: {
    now: "teraz",
    in_min: "za {min} min",
    in_1_min: "za 1 min",
    no_departures: "Brak dostępnych odjazdów",
    no_trip_data: "Brak danych o podróży",
    entity_unavailable: "Encja niedostępna",
    please_define_entity: "Wybierz encję",
    alternative_connections: "Alternatywne połączenia",
    connection_at_risk: "Połączenie zagrożone",
    risk: "ryzyko",
    risk_low: "Niskie ryzyko",
    risk_medium: "Średnie ryzyko",
    risk_high: "Wysokie ryzyko",
    min_transfer: "Czas przesiadki",
    transfer: "Przesiadka",
    transfers: "przesiadki",
    platform: "Peron",
    time: "Czas",
    line: "Linia",
    destination: "Kierunek",
    track: "Tor",
    table_layout: "Tabela (Tablica odjazdów)",
    compact_layout: "Kompaktowy (Chipy)",
    trip_layout: "Podróż (Trasa)",
    next_layout: "Następny odjazd (Widget)",
    entity: "Encja",
    layout: "Układ",
    theme: "Motyw",
    theme_ha: "Home Assistant (natywny)",
    max_departures: "Maks. odjazdów",
    show_header: "Pokaż nagłówek",
    show_platform: "Pokaż peron",
    show_delay: "Pokaż opóźnienie",
    show_realtime: "Pokaż wskaźnik czasu rzeczywistego",
    display_options: "Opcje wyświetlania",
    line_filter: "Filtr linii",
    line_filter_hint: "Pokaż tylko te linie (oddzielone przecinkami, np. U6, S1, RE5). Zostaw puste, aby pokazać wszystkie.",
    destination_filter: "Filtr kierunku",
    destination_filter_hint: "Pokaż tylko odjazdy z pasującym kierunkiem (oddzielone przecinkami, częściowe dopasowanie, np. Duisburg, Lotnisko). Zostaw puste, aby pokazać wszystkie.",
    filters: "Filtry",
    trip_filter_note: "Filtry linii i kierunku działają tylko na tablicach odjazdów. Połączenia filtrujesz w samym urządzeniu: Ustawienia → Urządzenia i usługi → twoje urządzenie podróży → Konfiguruj.",
  },
  it: {
    now: "adesso",
    in_min: "tra {min} min",
    in_1_min: "tra 1 min",
    no_departures: "Nessuna partenza disponibile",
    no_trip_data: "Nessun dato di viaggio disponibile",
    entity_unavailable: "Entità non disponibile",
    please_define_entity: "Seleziona un'entità",
    alternative_connections: "Connessioni alternative",
    connection_at_risk: "Connessione a rischio",
    risk: "rischio",
    risk_low: "Rischio basso",
    risk_medium: "Rischio medio",
    risk_high: "Rischio alto",
    min_transfer: "Tempo di cambio",
    transfer: "Cambio",
    transfers: "cambi",
    platform: "Bin.",
    time: "Orario",
    line: "Linea",
    destination: "Destinazione",
    track: "Binario",
    table_layout: "Tabella (Pannello partenze)",
    compact_layout: "Compatto (Chip)",
    trip_layout: "Viaggio (Percorso)",
    next_layout: "Prossima partenza (Widget)",
    entity: "Entità",
    layout: "Layout",
    theme: "Tema",
    theme_ha: "Home Assistant (nativo)",
    max_departures: "Max. partenze",
    show_header: "Mostra intestazione",
    show_platform: "Mostra binario",
    show_delay: "Mostra ritardo",
    show_realtime: "Mostra indicatore tempo reale",
    display_options: "Opzioni di visualizzazione",
    line_filter: "Filtro linee",
    line_filter_hint: "Mostra solo queste linee (separate da virgola, es. U6, S1, RE5). Lascia vuoto per mostrare tutto.",
    destination_filter: "Filtro destinazione",
    destination_filter_hint: "Mostra solo le partenze con destinazione corrispondente (separate da virgola, corrispondenza parziale, es. Duisburg, Aeroporto). Lascia vuoto per mostrare tutto.",
    filters: "Filtri",
    trip_filter_note: "I filtri di linea e destinazione valgono solo per i tabelloni delle partenze. Filtra le connessioni sul dispositivo stesso: Impostazioni → Dispositivi e servizi → il tuo dispositivo viaggio → Configura.",
  },
};

export function localize(lang: string, key: string, params?: Record<string, string | number>): string {
  const langCode = lang?.substring(0, 2).toLowerCase() || "en";
  const strings = translations[langCode] || translations["en"];
  let text = strings[key] || translations["en"][key] || key;

  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(`{${k}}`, String(v));
    }
  }

  return text;
}
